name: Update Translation Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  update-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run translation update script
        run: python .github/scripts/update_languages.py

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update translation coverage table
          branch: main
          file_pattern: README.md
